	"penis":       true,
	"vagina":       true,
	"bosta":       true,
	"idiota":       true,
	"babaca":       true,
	"merda":       true,
	"filho da puta":       true,
	"desgraça":       true,
	"desgraca":       true,
	"cabrumco":       true,
	"pau":       true,
	"toma no cu":       true,
	"tomar no kur":       true,
	"diabo":       true,
	"lucifer":       true,
	"pau":       true,
	"pica":       true,
	"porra":       true,
	"teu cu":       true,
	"buceta":       true,
	"puta merda":       true,
	"teu cu":       true,
